import {SCHEMA} from "./schema.js";
import {VERSION,POINTERS,readPointers,servingSignature} from "./projector.js";
const UNIVERSE_POINTER="universe/current.json",norm=x=>String(x||"").replace(/^sha256:/,""),req=(x,k)=>{if(x?.[k]===undefined||x[k]===null||x[k]==="")throw Error("missing "+k);return x[k]};
const digest=async b=>"sha256:"+[...new Uint8Array(await crypto.subtle.digest("SHA-256",b))].map(x=>x.toString(16).padStart(2,"0")).join("");
async function object(env,key){const x=await env.R2_BUCKET.get(key);if(!x)throw Error("missing R2 object: "+key);return x}
async function payload(env,p){const[d,m]=await Promise.all([object(env,p.jsonl_key),object(env,p.metadata_key)]),stored=await d.arrayBuffer(),meta=await m.json();let bytes=stored;if(p.representation==="ndjson+gzip"){const sh=await digest(stored);if(norm(sh)!==norm(p.stored_hash)||norm(sh)!==norm(meta.storage?.stored_sha256))throw Error("checkpoint stored checksum mismatch");bytes=await new Response(new Blob([stored]).stream().pipeThrough(new DecompressionStream("gzip"))).arrayBuffer();if(bytes.byteLength!==p.logical_bytes||bytes.byteLength!==meta.storage?.logical_bytes)throw Error("checkpoint logical size mismatch")}const actual=await digest(bytes);if(norm(actual)!==norm(p.source_hash)||norm(actual)!==norm(meta.source_hash)||(meta.storage?.logical_sha256&&norm(actual)!==norm(meta.storage.logical_sha256)))throw Error("checkpoint checksum mismatch");return{bytes,meta,hash:actual,pointer:p}}
async function rows(env,p){const x=await payload(env,p);return{...x,rows:new TextDecoder().decode(x.bytes).split(/\r?\n/).filter(Boolean).map(JSON.parse)}}
async function universe(env){const p=await(await object(env,UNIVERSE_POINTER)).json(),x=await(await object(env,p.membership_key)).json(),m=new Map;for(const r of x.records||[])if(r?.security_id&&r?.ticker)m.set(String(r.security_id),String(r.ticker));return{p,m}}
function mapUnique(a,k){const m=new Map;for(const x of a){const id=req(x,k);if(m.has(id))throw Error("duplicate "+k+": "+id);m.set(id,x)}return m}
function exact(row,c){if(!c||String(row.security_id)!==String(c.security_id))throw Error("candidate identity mismatch: "+row.candidate_id);if(row.signal_date!=null&&row.signal_date!==c.signal_date)throw Error("candidate signal date mismatch");if(row.pivot_level!==c.pivot_level)throw Error("candidate pivot mismatch")}
async function insertBatch(db,table,id,items){if(!items.length)return;await db.prepare(`INSERT INTO ${table}(id,payload) SELECT json_extract(value,'$.${id}'),value FROM json_each(?)`).bind(JSON.stringify(items)).run()}
export async function syncProjectionBounded(env,pointers=null){
 await env.DB.batch(SCHEMA.map(x=>env.DB.prepare(x)));pointers||=await readPointers(env);const u=await universe(env);
 const[c,t,l]=await Promise.all([rows(env,pointers.candidates),rows(env,pointers.t1),rows(env,pointers.lifecycle)]),cm=mapUnique(c.rows,"candidate_id"),tm=mapUnique(t.rows,"candidate_id");mapUnique(l.rows,"position_id");
 if(t.meta.upstream_candidate_hash&&norm(t.meta.upstream_candidate_hash)!==norm(c.hash))throw Error("T1 upstream candidate hash mismatch");for(const x of t.rows)exact(x,cm.get(x.candidate_id));
 const o=await payload(env,pointers.opportunities),run={schema_version:VERSION,signature:servingSignature(pointers,u.p),as_of_date:l.pointer.as_of_date,opportunity_source_hash:o.hash,candidate_source_hash:c.hash,t1_source_hash:t.hash,lifecycle_source_hash:l.hash,opportunities:0,positions:l.rows.length,projected_at:new Date().toISOString()};run.run_id="projection-v7:"+await digest(new TextEncoder().encode(run.signature));
 await env.DB.batch([env.DB.prepare("DELETE FROM dashboard_validation"),env.DB.prepare("DELETE FROM dashboard_opportunities"),env.DB.prepare("DELETE FROM dashboard_positions")]);
 const bytes=new Uint8Array(o.bytes),dec=new TextDecoder(),batch=[];let start=0,seen=new Set;
 for(let i=0;i<=bytes.length;i++)if(i===bytes.length||bytes[i]===10){if(i>start){const x=JSON.parse(dec.decode(bytes.subarray(start,i)));["assessment_id","pattern_type","morphology_status","as_of_date","as_of_close","pivot_level"].forEach(k=>req(x,k));if(x.morphology_status!=="RECOGNIZED")throw Error("non-recognized row in opportunity snapshot");if(seen.has(x.assessment_id))throw Error("duplicate assessment_id: "+x.assessment_id);seen.add(x.assessment_id);const b=cm.get(x.assessment_id),e=b?tm.get(b.candidate_id):null;if(b&&(String(b.security_id)!==String(x.security_id)||b.pivot_level!==x.pivot_level))throw Error("snapshot/candidate identity mismatch: "+x.assessment_id);batch.push({...x,candidate_id:b?.candidate_id??null,ticker:x.ticker??u.m.get(String(x.security_id))??null,breakout_state:b?.breakout_state??null,volume_ratio:b?.breakout_volume_ratio??null,signal_date:b?.signal_date??null,t1_status:e?.entry_state??null,t1_open:e?.next_open??null,open_extension_pct:e?.open_extension_pct??null,entry_date:e?.fill_date??null,entry_price:e?.fill_price??null,source_hash:o.hash});run.opportunities++;if(batch.length===100){await insertBatch(env.DB,"dashboard_opportunities","assessment_id",batch);batch.length=0}}start=i+1}
 await insertBatch(env.DB,"dashboard_opportunities","assessment_id",batch);
 for(let i=0;i<l.rows.length;i+=100){const out=l.rows.slice(i,i+100).map(x=>{const candidate=cm.get(req(x,"candidate_id"));exact(x,candidate);const e=tm.get(x.candidate_id);if(!e)throw Error("missing exact T1 for lifecycle");return{...x,ticker:x.ticker??candidate.ticker??u.m.get(String(x.security_id))??null,pattern_type:candidate.pattern_type,assessment_id:x.candidate_id,as_of_date:l.pointer.as_of_date,source_hash:l.hash}});await insertBatch(env.DB,"dashboard_positions","position_id",out)}
 if(servingSignature(await readPointers(env),(await universe(env)).p)!==run.signature)throw Error("source pointers changed during projection; retry");
 const counts=await env.DB.prepare("SELECT (SELECT COUNT(*) FROM dashboard_opportunities) opportunities,(SELECT COUNT(*) FROM dashboard_positions) positions").first();if(counts.opportunities!==run.opportunities||counts.positions!==run.positions)throw Error("projection count mismatch");
 await env.DB.batch([env.DB.prepare("INSERT OR REPLACE INTO dashboard_validation(singleton,valid) VALUES(1,1)"),env.DB.prepare("INSERT INTO dashboard_current(singleton,payload) VALUES(1,?) ON CONFLICT(singleton) DO UPDATE SET payload=excluded.payload").bind(JSON.stringify(run))]);return run
}