const norm=x=>String(x||"").replace(/^sha256:/,"");
const digest=async b=>"sha256:"+[...new Uint8Array(await crypto.subtle.digest("SHA-256",b))].map(x=>x.toString(16).padStart(2,"0")).join("");
async function object(env,key){const x=await env.R2_BUCKET.get(key);if(!x)throw Error("missing R2 object: "+key);return x}
async function checkpoint(env,p){const[d,m]=await Promise.all([object(env,p.jsonl_key),object(env,p.metadata_key)]),b=await d.arrayBuffer(),meta=await m.json(),h=await digest(b);if(norm(h)!==norm(p.source_hash)||norm(h)!==norm(meta.source_hash))throw Error("historical checkpoint checksum mismatch");return{rows:new TextDecoder().decode(b).split(/\r?\n/).filter(Boolean).map(JSON.parse),meta,hash:h}}
async function indexed(env,stage,date){const x=await env.R2_BUCKET.get(`pattern-breakout/production/${stage}/by-signal-date/${date}.json`);return x?x.json():null}
async function candidatePointer(env,date,current){if(current.as_of_date===date)return current;const p=await indexed(env,"candidates",date);if(p)return p;if(typeof env.R2_BUCKET.list!=="function")throw Error("historical candidate index missing");const prefix=`pattern-breakout/production/candidates/runs/${date}/`,page=await env.R2_BUCKET.list({prefix});const keys=(page.objects||[]).map(x=>x.key).filter(x=>x.endsWith(".jsonl"));if(keys.length!==1)throw Error("historical candidate checkpoint is not uniquely resolvable");const key=keys[0],h=key.slice(prefix.length,-6);return{stage:"candidates",as_of_date:date,source_hash:"sha256:"+h,jsonl_key:key,metadata_key:prefix+h+".json"}}
async function t1Pointer(env,date,current){const p=await indexed(env,"t1-execution",date);if(p)return p;const c=await checkpoint(env,current);return c.meta?.summary?.signal_date===date?current:null}
export async function historicalOpportunities(env,date,pointers,{limit=100,offset=0}={}){
 const cp=await candidatePointer(env,date,pointers.candidates),c=await checkpoint(env,cp),tp=await t1Pointer(env,date,pointers.t1),t=tp?await checkpoint(env,tp):null,tm=new Map((t?.rows||[]).map(x=>[x.candidate_id,x]));
 return c.rows.slice(offset,offset+limit).map(x=>{const e=t&&norm(t.meta.upstream_candidate_hash)===norm(c.hash)?tm.get(x.candidate_id):null;return{...x,assessment_id:x.candidate_id,as_of_date:x.signal_date,morphology_status:"RECOGNIZED",volume_ratio:x.breakout_volume_ratio??null,t1_status:e?.entry_state??null,t1_open:e?.next_open??null,open_extension_pct:e?.open_extension_pct??null,entry_date:e?.fill_date??null,entry_price:e?.fill_price??null,source_hash:c.hash,historical:true}})
}
