import {SCHEMA} from "./schema.js";
export const VERSION="dashboard-projection-v7";
export const POINTERS={opportunities:"pattern-breakout/production/dashboard-opportunities/current.json",candidates:"pattern-breakout/production/candidates/current.json",t1:"pattern-breakout/production/t1-execution/current.json",lifecycle:"pattern-breakout/production/lifecycle/current.json",prices:"pattern-breakout/production/dashboard-prices/current.json"};
const UNIVERSE_POINTER="universe/current.json";
const norm=x=>String(x||"").replace(/^sha256:/,"");
const req=(x,k)=>{if(x?.[k]===undefined||x[k]===null||x[k]==="")throw Error("missing "+k);return x[k]};
const digest=async b=>"sha256:"+[...new Uint8Array(await crypto.subtle.digest("SHA-256",b))].map(x=>x.toString(16).padStart(2,"0")).join("");
async function object(env,key){const x=await env.R2_BUCKET.get(key);if(!x)throw Error("missing R2 object: "+key);return x}
export async function readPointers(env){return Object.fromEntries(await Promise.all(Object.entries(POINTERS).map(async([stage,key])=>{const p=await(await object(env,key)).json();["jsonl_key","metadata_key","source_hash","as_of_date"].forEach(k=>req(p,k));return[stage,p]})))}
export const servingSignature=(p,u)=>JSON.stringify([VERSION,...Object.keys(POINTERS).map(k=>[p[k].source_hash,p[k].as_of_date]),["universe",u.snapshot_date,u.membership_key]]);
async function load(env,p){const[d,m]=await Promise.all([object(env,p.jsonl_key),object(env,p.metadata_key)]),stored=await d.arrayBuffer(),meta=await m.json();let bytes=stored;if(p.representation==="ndjson+gzip"){const sh=await digest(stored);if(norm(sh)!==norm(p.stored_hash)||norm(sh)!==norm(meta.storage?.stored_sha256))throw Error("checkpoint stored checksum mismatch");bytes=await new Response(new Blob([stored]).stream().pipeThrough(new DecompressionStream("gzip"))).arrayBuffer();if(bytes.byteLength!==p.logical_bytes||bytes.byteLength!==meta.storage?.logical_bytes)throw Error("checkpoint logical size mismatch")}else if(p.representation&&p.representation!=="ndjson")throw Error("unsupported checkpoint representation");const actual=await digest(bytes);if(norm(actual)!==norm(p.source_hash)||norm(actual)!==norm(meta.source_hash)||(meta.storage?.logical_sha256&&norm(actual)!==norm(meta.storage.logical_sha256)))throw Error("checkpoint checksum mismatch");return{pointer:p,meta,hash:actual,rows:new TextDecoder().decode(bytes).split(/\r?\n/).filter(Boolean).map(JSON.parse)}}
async function readUniversePointer(env){const p=await(await object(env,UNIVERSE_POINTER)).json();req(p,"snapshot_date");req(p,"membership_key");return p}
async function tickerMap(env,p=null){p||=await readUniversePointer(env);const payload=await(await object(env,p.membership_key)).json(),rows=payload.records;if(!Array.isArray(rows))throw Error("invalid universe membership records");const map=new Map;for(const x of rows)if(x?.security_id&&x?.ticker)map.set(String(x.security_id),String(x.ticker));return map}
function unique(rows,key){const m=new Map;for(const x of rows){const id=req(x,key);req(x,"security_id");if(m.has(id))throw Error("duplicate "+key+": "+id);m.set(id,x)}return m}
function exact(row,c){if(!c||String(row.security_id)!==String(c.security_id))throw Error("candidate identity mismatch: "+row.candidate_id);if(row.signal_date!=null&&row.signal_date!==c.signal_date)throw Error("candidate signal date mismatch");if(row.pivot_level!==c.pivot_level)throw Error("candidate pivot mismatch")}
export async function buildProjection(env,pointers=null){
 pointers||=await readPointers(env);const universe=await readUniversePointer(env);const[o,c,t,l,tickers]=await Promise.all([...Object.values(pointers).map(p=>load(env,p)),tickerMap(env,universe)]),om=unique(o.rows,"assessment_id"),cm=unique(c.rows,"candidate_id"),tm=unique(t.rows,"candidate_id");unique(l.rows,"position_id");
 if(t.meta.upstream_candidate_hash&&norm(t.meta.upstream_candidate_hash)!==norm(c.hash))throw Error("T1 upstream candidate hash mismatch");for(const x of t.rows)exact(x,cm.get(x.candidate_id));
 const opportunities=o.rows.map(x=>{["assessment_id","pattern_type","morphology_status","as_of_date","as_of_close","pivot_level"].forEach(k=>req(x,k));if(x.morphology_status!=="RECOGNIZED")throw Error("non-recognized row in opportunity snapshot");const b=cm.get(x.assessment_id);if(b){exact(b,{...b,candidate_id:b.candidate_id});if(String(b.security_id)!==String(x.security_id)||b.pivot_level!==x.pivot_level)throw Error("snapshot/candidate identity mismatch: "+x.assessment_id)}const e=b?tm.get(b.candidate_id):null;return{...x,candidate_id:b?.candidate_id??null,ticker:x.ticker??tickers.get(String(x.security_id))??null,breakout_state:b?.breakout_state??null,volume_ratio:b?.breakout_volume_ratio??null,signal_date:b?.signal_date??null,t1_status:e?.entry_state??null,t1_open:e?.next_open??null,open_extension_pct:e?.open_extension_pct??null,entry_date:e?.fill_date??null,entry_price:e?.fill_price??null,source_hash:o.hash}});
 const positions=l.rows.map(x=>{const candidate=cm.get(req(x,"candidate_id"));exact(x,candidate);if(!["OPEN","EXIT_PENDING","NOT_OPENED","CLOSED","NOT_EVALUABLE"].includes(req(x,"state")))throw Error("invalid lifecycle state");const e=tm.get(x.candidate_id);if(!e)throw Error("missing exact T1 for lifecycle");if(["OPEN","EXIT_PENDING","CLOSED"].includes(x.state)&&(e.entry_state!=="EXECUTED_T1_OPEN"||x.entry_date!==e.fill_date||x.entry_price!==e.fill_price))throw Error("lifecycle entry mismatch");return{...x,ticker:x.ticker??candidate.ticker??tickers.get(String(x.security_id))??null,pattern_type:candidate.pattern_type,assessment_id:x.candidate_id,as_of_date:l.pointer.as_of_date,source_hash:l.hash}});
 return{pointers,universe,opportunities,positions,stages:{o,c,t,l}};
}
export async function ensureSchema(db){await db.batch(SCHEMA.map(x=>db.prepare(x)))}
export async function currentRun(db){const x=await db.prepare("SELECT payload FROM dashboard_current WHERE singleton=1").first();return x?JSON.parse(x.payload):null}
export async function validCurrent(db,run){if(!run)return false;if(["dashboard-projection-v8","dashboard-projection-v9"].includes(run.schema_version)){const c=await db.prepare("SELECT (SELECT COUNT(*) FROM dashboard_opportunities_v8 WHERE generation=?) opportunities,(SELECT COUNT(*) FROM dashboard_positions_v8 WHERE generation=?) positions").bind(run.generation,run.generation).first();return c.opportunities===run.opportunities&&c.positions===run.positions}if(run.schema_version!==VERSION)return false;const c=await db.prepare("SELECT (SELECT COUNT(*) FROM dashboard_opportunities) opportunities,(SELECT COUNT(*) FROM dashboard_positions) positions").first();return c.opportunities===run.opportunities&&c.positions===run.positions}
export async function syncProjection(env,pointers=null){
 const p=await buildProjection(env,pointers),run={schema_version:VERSION,signature:servingSignature(p.pointers,p.universe),as_of_date:p.stages.l.pointer.as_of_date,opportunity_source_hash:p.stages.o.hash,candidate_source_hash:p.stages.c.hash,t1_source_hash:p.stages.t.hash,lifecycle_source_hash:p.stages.l.hash,opportunities:p.opportunities.length,positions:p.positions.length,projected_at:new Date().toISOString()};run.run_id="projection-v6:"+await digest(new TextEncoder().encode(run.signature));
 const q=[env.DB.prepare("DELETE FROM dashboard_opportunities"),env.DB.prepare("DELETE FROM dashboard_positions")];for(const[table,rows,id]of[["dashboard_opportunities",p.opportunities,"assessment_id"],["dashboard_positions",p.positions,"position_id"]])for(let i=0;i<rows.length;i+=100)q.push(env.DB.prepare(`INSERT INTO ${table}(id,payload) SELECT json_extract(value,'$.${id}'),value FROM json_each(?)`).bind(JSON.stringify(rows.slice(i,i+100))));
 q.push(env.DB.prepare("INSERT OR REPLACE INTO dashboard_validation(singleton,valid) SELECT 1,CASE WHEN (SELECT COUNT(*) FROM dashboard_opportunities)=? AND (SELECT COUNT(*) FROM dashboard_positions)=? THEN 1 ELSE 0 END").bind(run.opportunities,run.positions));q.push(env.DB.prepare("INSERT INTO dashboard_current(singleton,payload) VALUES(1,?) ON CONFLICT(singleton) DO UPDATE SET payload=excluded.payload").bind(JSON.stringify(run)));
 if(servingSignature(await readPointers(env),await readUniversePointer(env))!==run.signature)throw Error("source pointers changed during projection; retry");await env.DB.batch(q);return run;
}
const syncing=new WeakMap;
export async function syncIfNeeded(env){if(syncing.has(env.DB))return syncing.get(env.DB);const work=(async()=>{await ensureSchema(env.DB);const p=await readPointers(env),u=await readUniversePointer(env),r=await currentRun(env.DB);return r?.signature===servingSignature(p,u)&&await validCurrent(env.DB,r)?r:syncProjection(env,p)})();syncing.set(env.DB,work);try{return await work}finally{syncing.delete(env.DB)}}
