import {SCHEMA} from "./schema.js";
export const VERSION="dashboard-projection-v16-separated-event-current";
const CURRENT="pattern-breakout/production/dashboard-v2/current.json",EVENTS="pattern-breakout/production/dashboard-events-v2/current.json",PRICE="pattern-breakout/production/dashboard-prices/current.json",OPPORTUNITIES="pattern-breakout/production/dashboard-opportunities/current.json";
const req=(x,k)=>{if(x?.[k]===undefined||x[k]===null||x[k]==="")throw Error("missing "+k);return x[k]};
async function object(env,key){const x=await env.R2_BUCKET.get(key);if(!x)throw Error("missing R2 object: "+key);return x}
export async function readPointers(env){const m=await(await object(env,CURRENT)).json();if(m.schema_version!=="dashboard-v2-current-v1")throw Error("invalid dashboard v2 current manifest");let event;try{event=await(await object(env,EVENTS)).json()}catch(e){event={...req(m.stages,"events"),schema_version:"dashboard-events-v2-current-v1",stage:"breakout-events-v2"}}if(event.schema_version!=="dashboard-events-v2-current-v1"||event.stage!=="breakout-events-v2")throw Error("invalid dashboard event current pointer");const positionSignal=req(m,"signal_date"),out={};for(const k of ["execution","lifecycle"]){const p=req(m.stages,k);["jsonl_key","metadata_key","source_hash","signal_date"].forEach(x=>req(p,x));if(p.signal_date!==positionSignal)throw Error("dashboard v2 position cohort mismatch");out[k]={...p,as_of_date:p.signal_date}}["jsonl_key","metadata_key","source_hash","signal_date"].forEach(x=>req(event,x));out.events={...event,as_of_date:event.signal_date};const price=await(await object(env,PRICE)).json();["jsonl_key","metadata_key","source_hash","as_of_date"].forEach(x=>req(price,x));out.prices=price;const opp=await(await object(env,OPPORTUNITIES)).json();["jsonl_key","metadata_key","source_hash","as_of_date"].forEach(x=>req(opp,x));out.opportunities=opp;return out}
export async function ensureSchema(db){await db.batch(SCHEMA.map(x=>db.prepare(x)))}
export async function currentRun(db){const x=await db.prepare("SELECT payload FROM projection_state WHERE singleton=1").first();return x?JSON.parse(x.payload):null}
export async function validCurrent(db,run){if(!run||run.schema_version!==VERSION)return false;const c=await db.prepare("SELECT (SELECT COUNT(*) FROM current_breakout_events WHERE generation=?) events,(SELECT COUNT(*) FROM current_positions WHERE generation=?) positions,(SELECT COUNT(*) FROM current_opportunities WHERE generation=?) opportunities").bind(run.generation,run.generation,run.generation).first();return c.events===run.breakout_events&&c.positions===run.positions&&c.opportunities===run.opportunities}
