import {SCHEMA} from "./schema.js";
import {POINTERS,readPointers,servingSignature} from "./projector.js";
const SERVING="pattern-breakout/production/dashboard-serving/current.json",UNIVERSE="universe/current.json",norm=x=>String(x||"").replace(/^sha256:/,"");
const req=(x,k)=>{if(x?.[k]===undefined||x[k]===null||x[k]==="")throw Error("missing "+k);return x[k]};
const digest=async b=>"sha256:"+[...new Uint8Array(await crypto.subtle.digest("SHA-256",b))].map(x=>x.toString(16).padStart(2,"0")).join("");
async function object(env,key){const x=await env.R2_BUCKET.get(key);if(!x)throw Error("missing R2 object: "+key);return x}
async function jsonObject(env,key){return(await object(env,key)).json()}
async function smallRows(env,p){const d=await object(env,p.jsonl_key),b=await d.arrayBuffer(),h=await digest(b);if(norm(h)!==norm(p.source_hash))throw Error("small checkpoint checksum mismatch");return new TextDecoder().decode(b).split(/\r?\n/).filter(Boolean).map(JSON.parse)}
function unique(a,k){const m=new Map;for(const x of a){const id=req(x,k);if(m.has(id))throw Error("duplicate "+k+": "+id);m.set(id,x)}return m}
async function context(env,p){const[c,t]=await Promise.all([smallRows(env,p.candidates),smallRows(env,p.t1)]),cm=unique(c,"candidate_id"),tm=unique(t,"candidate_id"),up=await jsonObject(env,UNIVERSE),um=await jsonObject(env,up.membership_key),tickers=new Map;for(const x of um.records||[])if(x?.security_id&&x?.ticker)tickers.set(String(x.security_id),String(x.ticker));return{cm,tm,up,tickers}}
async function manifest(env){const sp=await jsonObject(env,SERVING),o=await object(env,sp.manifest_key),b=await o.arrayBuffer(),h=await digest(b);if(norm(h)!==norm(sp.manifest_hash))throw Error("serving manifest checksum mismatch");const m=JSON.parse(new TextDecoder().decode(b));if(m.source_hash!==sp.source_hash||m.record_count!==sp.record_count||m.shard_count!==sp.shard_count)throw Error("serving manifest/pointer mismatch");return{sp,m}}
async function shardRows(env,s){const o=await object(env,s.key),stored=await o.arrayBuffer();if(norm(await digest(stored))!==norm(s.stored_sha256))throw Error("serving shard stored checksum mismatch");const raw=await new Response(new Blob([stored]).stream().pipeThrough(new DecompressionStream("gzip"))).arrayBuffer();if(raw.byteLength!==s.logical_bytes||norm(await digest(raw))!==norm(s.logical_sha256))throw Error("serving shard logical checksum mismatch");const rows=new TextDecoder().decode(raw).split(/\r?\n/).filter(Boolean).map(JSON.parse);if(rows.length!==s.record_count)throw Error("serving shard record count mismatch");return rows}
async function insert(db,table,g,id,rows){for(let i=0;i<rows.length;i+=100)await db.prepare(`INSERT INTO ${table}(generation,id,payload) SELECT ?,json_extract(value,'$.${id}'),value FROM json_each(?)`).bind(g,JSON.stringify(rows.slice(i,i+100))).run()}
export async function syncProjectionV8(env,maxShards=10){
 await env.DB.batch(SCHEMA.map(x=>env.DB.prepare(x)));const pointers=await readPointers(env),{sp,m}=await manifest(env);if(sp.source_hash!==pointers.opportunities.source_hash)throw Error("serving shards do not match current opportunity checkpoint");
 const {cm,tm,up,tickers}=await context(env,pointers),signature=servingSignature(pointers,up),generation=norm(sp.source_hash),old=await env.DB.prepare("SELECT payload FROM dashboard_sync_v8 WHERE singleton=1").first();let state=old?JSON.parse(old.payload):null;
 if(!state||state.generation!==generation||state.signature!==signature){await env.DB.prepare("DELETE FROM dashboard_opportunities_v8 WHERE generation=?").bind(generation).run();state={generation,signature,next_shard:0,shard_count:m.shard_count,inserted:0,status:"BUILDING"}}
 const end=Math.min(state.next_shard+maxShards,m.shard_count);
 for(let i=state.next_shard;i<end;i++){const s=m.shards[i];if(s.index!==i)throw Error("non-contiguous serving manifest");const raw=await shardRows(env,s),out=raw.map(x=>{["assessment_id","pattern_type","morphology_status","as_of_date","as_of_close","pivot_level"].forEach(k=>req(x,k));if(x.morphology_status!=="RECOGNIZED")throw Error("non-recognized opportunity");const b=cm.get(x.assessment_id),e=b?tm.get(b.candidate_id):null;if(b&&(String(b.security_id)!==String(x.security_id)||b.pivot_level!==x.pivot_level))throw Error("snapshot/candidate identity mismatch: "+x.assessment_id);return{...x,candidate_id:b?.candidate_id??null,ticker:x.ticker??tickers.get(String(x.security_id))??null,breakout_state:b?.breakout_state??null,volume_ratio:b?.breakout_volume_ratio??null,signal_date:b?.signal_date??null,t1_status:e?.entry_state??null,t1_open:e?.next_open??null,open_extension_pct:e?.open_extension_pct??null,entry_date:e?.fill_date??null,entry_price:e?.fill_price??null,source_hash:sp.source_hash}});await insert(env.DB,"dashboard_opportunities_v8",generation,"assessment_id",out);state.next_shard=i+1;state.inserted+=out.length;await env.DB.prepare("INSERT INTO dashboard_sync_v8(singleton,payload) VALUES(1,?) ON CONFLICT(singleton) DO UPDATE SET payload=excluded.payload").bind(JSON.stringify(state)).run()}
 if(state.next_shard<m.shard_count)return{schema_version:"dashboard-projection-v8",status:"BUILDING",generation,next_shard:state.next_shard,shard_count:m.shard_count,inserted:state.inserted,record_count:m.record_count};
 const l=await smallRows(env,pointers.lifecycle),positions=l.map(x=>{const b=cm.get(req(x,"candidate_id")),e=tm.get(x.candidate_id);if(!b||!e)throw Error("lifecycle identity mismatch");return{...x,ticker:x.ticker??b.ticker??tickers.get(String(x.security_id))??null,pattern_type:b.pattern_type,assessment_id:x.candidate_id,as_of_date:pointers.lifecycle.as_of_date,source_hash:pointers.lifecycle.source_hash}});await env.DB.prepare("DELETE FROM dashboard_positions_v8 WHERE generation=?").bind(generation).run();await insert(env.DB,"dashboard_positions_v8",generation,"position_id",positions);
 if(servingSignature(await readPointers(env),(await jsonObject(env,UNIVERSE)))!==signature)throw Error("source pointers changed during projection");
 const counts=await env.DB.prepare("SELECT (SELECT COUNT(*) FROM dashboard_opportunities_v8 WHERE generation=?) opportunities,(SELECT COUNT(*) FROM dashboard_positions_v8 WHERE generation=?) positions").bind(generation,generation).first();if(counts.opportunities!==m.record_count||counts.positions!==positions.length)throw Error("v8 projection count mismatch");
 const run={schema_version:"dashboard-projection-v8",generation,signature,as_of_date:pointers.lifecycle.as_of_date,opportunity_source_hash:sp.source_hash,candidate_source_hash:pointers.candidates.source_hash,t1_source_hash:pointers.t1.source_hash,lifecycle_source_hash:pointers.lifecycle.source_hash,opportunities:counts.opportunities,positions:counts.positions,projected_at:new Date().toISOString()};run.run_id="projection-v8:"+generation;state.status="READY";await env.DB.batch([env.DB.prepare("INSERT INTO dashboard_current(singleton,payload) VALUES(1,?) ON CONFLICT(singleton) DO UPDATE SET payload=excluded.payload").bind(JSON.stringify(run)),env.DB.prepare("INSERT OR REPLACE INTO dashboard_validation(singleton,valid) VALUES(1,1)"),env.DB.prepare("UPDATE dashboard_sync_v8 SET payload=? WHERE singleton=1").bind(JSON.stringify(state))]);return{...run,status:"READY"}
}