import test from "node:test";import {createHash} from "node:crypto";import assert from "node:assert/strict";import worker from "../_worker.js";import {localEnvironment} from "../local/environment.mjs";import {fixtureRows} from "../local/fixtures.mjs";import {currentRun} from "../d1/runtime.js";import {syncProjectionV9} from "../d1/compact.js";
const ensureReady=async env=>{await syncProjectionV9(env);return env};
const call=(env,path)=>worker.fetch(new Request("http://local"+path),env).then(async r=>({status:r.status,body:await r.json()}));
test("GET serving path never invokes projection sync",async()=>{const env=localEnvironment();await ensureReady(env);env.R2_BUCKET={get(){throw Error("GET serving path touched R2")}};const h=await call(env,"/api/health");assert.equal(h.status,200);assert.equal(h.body.status,"READY");const o=await call(env,"/api/opportunities?limit=1");assert.equal(o.status,200);assert.equal(o.body.length,0);const e=await call(env,"/api/breakout-events?limit=1");assert.equal(e.status,200);assert.equal(e.body.length,1)});
test("compact projection does not require legacy dashboard-opportunities pointer",async()=>{const env=localEnvironment();env._fixtureObjects.delete("pattern-breakout/production/dashboard-opportunities/current.json");const r=await syncProjectionV9(env);assert.equal(r.status,"READY");assert.equal(r.schema_version,"dashboard-projection-v13-clean");assert.equal(r.opportunities,0);assert.equal(r.breakout_events,48);assert.equal(r.positions,20)});

test("V13 clean separates opportunities, breakout events, and positions",async()=>{const env=localEnvironment();const r=await syncProjectionV9(env);assert.equal(r.status,"READY");assert.equal(r.schema_version,"dashboard-projection-v13-clean");assert.equal(r.opportunities,0);assert.equal(r.breakout_events,48);assert.equal(r.positions,20);const h=await call(env,"/api/health");assert.equal(h.body.status,"READY");assert.equal(h.body.opportunity_count,0);assert.equal(h.body.breakout_event_count,48);assert.deepEqual(h.body.position_states,[{state:"OPEN",count:20}]);const o=await call(env,"/api/opportunities?limit=500");assert.equal(o.body.length,0);const e=await call(env,"/api/breakout-events?limit=500");assert.equal(e.body.length,48);assert.ok(e.body.every(x=>x.event_id&&x.source_hash));const p=await call(env,"/api/positions?limit=500");assert.equal(p.body.length,20);assert.ok(p.body.every(x=>x.execution_id&&Array.isArray(x.supporting_event_ids)));});



test("history is additive and idempotent across verified generations",async()=>{const env=localEnvironment();await syncProjectionV9(env);let h=env.DB.prepare("SELECT signal_date,COUNT(*) count FROM historical_breakout_events GROUP BY signal_date").all().results.map(x=>({...x}));assert.deepEqual(h,[{signal_date:"2026-09-17",count:48}]);await syncProjectionV9(env);h=env.DB.prepare("SELECT signal_date,COUNT(*) count FROM historical_breakout_events GROUP BY signal_date").all().results.map(x=>({...x}));assert.deepEqual(h,[{signal_date:"2026-09-17",count:48}]);const manifest=JSON.parse(env._fixtureObjects.get("pattern-breakout/production/dashboard-v2/current.json"));for(const [alias,stage] of [["events","breakout-events-v2"],["execution","security-execution-v2"],["lifecycle","lifecycle-v2"]]){const old=manifest.stages[alias],raw=env._fixtureObjects.get(old.jsonl_key).toString(),rows=raw.trim().split("\n").map(JSON.parse).map(x=>x.signal_date?{...x,signal_date:"2026-09-21"}:x),body=Buffer.from(rows.map(x=>JSON.stringify(x)).join("\n")+"\n"),source_hash="sha256:"+createHash("sha256").update(body).digest("hex"),key=`fixture/${stage}-21.jsonl`,mkey=`fixture/${stage}-21.json`,meta={source_hash,signal_date:"2026-09-21"};if(stage==="lifecycle-v2")meta.upstream_security_execution_hash=manifest.stages.execution.source_hash;env._fixtureObjects.set(key,body);env._fixtureObjects.set(mkey,Buffer.from(JSON.stringify(meta)));manifest.stages[alias]={jsonl_key:key,metadata_key:mkey,source_hash,signal_date:"2026-09-21"}}manifest.stages.lifecycle.metadata_key="fixture/lifecycle-v2-21.json";const lm=JSON.parse(env._fixtureObjects.get(manifest.stages.lifecycle.metadata_key));lm.upstream_security_execution_hash=manifest.stages.execution.source_hash;env._fixtureObjects.set(manifest.stages.lifecycle.metadata_key,Buffer.from(JSON.stringify(lm)));manifest.signal_date="2026-09-21";env._fixtureObjects.set("pattern-breakout/production/dashboard-v2/current.json",Buffer.from(JSON.stringify(manifest)));await syncProjectionV9(env);h=env.DB.prepare("SELECT signal_date,COUNT(*) count FROM historical_breakout_events GROUP BY signal_date ORDER BY signal_date").all().results.map(x=>({...x}));assert.deepEqual(h,[{signal_date:"2026-09-17",count:48},{signal_date:"2026-09-21",count:48}]);const run=await currentRun(env.DB);assert.equal(run.event_as_of_date,"2026-09-21");});
test("historical opportunities never alias breakout events",async()=>{const env=localEnvironment();await syncProjectionV9(env);const o=await call(env,"/api/opportunities?signal_date=2026-09-16");assert.equal(o.status,200);assert.deepEqual(o.body,[])});

test("authenticated history sync is idempotent",async()=>{const env=localEnvironment();env.SYNC_TOKEN="test";await syncProjectionV9(env);const req=()=>worker.fetch(new Request("http://local/api/admin/sync-history?signal_date=2026-09-17",{method:"POST",headers:{authorization:"Bearer test"}}),env).then(r=>r.json());const a=await req(),b=await req();assert.equal(a.breakout_events,48);assert.equal(b.breakout_events,48);const n=env.DB.prepare("SELECT COUNT(*) n FROM historical_breakout_events WHERE signal_date=?").get("2026-09-17").n;assert.equal(n,48)});
